### ISSUE TITLE
openbazaar not merging

### ISSUE THREAD

**Issue by sebastianheyn** [l29ah/booboo#22]
First of all, it throws this error message:

/var/lib/layman/booboo/net-p2p/openbazaar/openbazaar-9999.ebuild: line 39: enewuser: command not found

Then it hangs on on the username/password forever
- Fetching https://github.com/OpenBazaar/OpenBazaar.git ...
  git fetch https://github.com/OpenBazaar/OpenBazaar.git +HEAD:refs/git-r3/HEAD
  Username for 'https://github.com': 

Can you provide username/password inside the ebuild?

**Comment by ElonSatoshi** [comment]
https://github.com/OpenBazaar/OpenBazaar.git doesn't exist anymore, openbazaar is now at https://github.com/OpenBazaar/Openbazaar-go.git

**Comment by l29ah** [comment]
See https://github.com/l29ah/booboo/issues/23#issuecomment-247402555
