### ISSUE TITLE
openbazaar-server not able to merge

### ISSUE THREAD

**Issue by sebastianheyn** [l29ah/booboo#23]
when trying to merge the bazaar-server, it throws a lot of python errors

maybe some dependencies are missing in the ebuild?

market/btcprice.py: 75: [E:syntax-error] -- invalid syntax
************\* Module market.network
market/network.py: 83: [E:syntax-error] -- invalid syntax
************\* Module market.contracts
market/contracts.py:547: [E:syntax-error] -- invalid syntax
************\* Module market.protocol
market/protocol.py:282: [E:syntax-error] -- invalid syntax
************\* Module market.transactions
market/transactions.py:174: [I:locally-disabled] -- Locally disabling cell-var-from-loop (W0640)
market/transactions.py:  4: [F:import-error] -- Unable to import 'bitcointools'
market/transactions.py:  5: [E:no-name-in-module] -- No name 'SelectParams' in module 'bitcoin'
market/transactions.py:  6: [E:no-name-in-module] -- No name 'core' in module 'bitcoin'
market/transactions.py:  6: [F:import-error] -- Unable to import 'bitcoin.core'
market/transactions.py:  7: [E:no-name-in-module] -- No name 'core' in module 'bitcoin'
market/transactions.py:  7: [F:import-error] -- Unable to import 'bitcoin.core.script'
market/transactions.py:  8: [E:no-name-in-module] -- No name 'core' in module 'bitcoin'
market/transactions.py:  8: [F:import-error] -- Unable to import 'bitcoin.core.scripteval'
market/transactions.py:  9: [E:no-name-in-module] -- No name 'wallet' in module 'bitcoin'
market/transactions.py:  9: [F:import-error] -- Unable to import 'bitcoin.wallet'
market/transactions.py: 10: [F:import-error] -- Unable to import 'config' (invalid syntax (<string>, line 161))
************\* Module market.moderation
market/moderation.py:  3: [F:import-error] -- Unable to import 'nacl.signing'
market/moderation.py:  8: [F:import-error] -- Unable to import 'config' (invalid syntax (<string>, line 161))
market/moderation.py: 11: [E:no-name-in-module] -- No name 'keychain' in module 'keys'
market/moderation.py: 11: [F:import-error] -- Unable to import 'keys.keychain' (Missing parentheses in call to 'print' (<string>, line 36))
market/moderation.py: 12: [E:no-name-in-module] -- No name 'contracts' in module 'market'
market/moderation.py: 12: [F:import-error] -- Unable to import 'market.contracts' (invalid syntax (<string>, line 547))
FAIL: Detected 51 files with errors.
Makefile:14: recipe for target 'pycheck' failed

**Comment by l29ah** [comment]
On Wed, Sep 14, 2016 at 10:51:29PM -0700, sebastianheyn wrote:
> when trying to merge the bazaar-server, it throws a lot of python errors
> 
> maybe some dependencies are missing in the ebuild?

Actually, i don't remember if i succeeded making it work at all. They have a kinda sick homebrew idea of how all this stuff must be installed and work, AFAIR. Anyways, patches are welcome.
net-p2p/openbazaar is deprecated (as they have split their repo) and net-p2p/openbazaar-server is unfinished, and was committed incidentally.

-- 
()  ascii ribbon campaign - against html mail
/\  http://arc.pasp.de/   - against proprietary attachments

**Comment by sebastianheyn** [comment]
understood. thanks.

**Comment by l29ah** [comment]
openbazaar is abandoned by its authors.
