### ISSUE TITLE
uzbl error in depend phase

### ISSUE THREAD

**Issue by stakewinner00** [l29ah/booboo#24]
When emergin uzbl i get the next error message:

```
Calculating dependencies \ * ERROR: www-client/uzbl-9999-r1::booboo failed (depend phase):
 *   use() calls are not allowed in global scope
 * 
 * Call stack:
 *             ebuild.sh, line 606:  Called source '/var/lib/layman/booboo/www-client/uzbl/uzbl-9999-r1.ebuild'
 *   uzbl-9999-r1.ebuild, line  18:  Called use 'experimental'
 *             ebuild.sh, line  78:  Called die
 * The specific snippet of code:
 *   		eval "${x}() { die \"\${FUNCNAME}() calls are not allowed in global scope\"; }"
 * 
 * If you need support, post the output of `emerge --info '=www-client/uzbl-9999-r1::booboo'`,
 * the complete build log and the output of `emerge -pqv '=www-client/uzbl-9999-r1::booboo'`.
 * Working directory: '/usr/lib64/python2.7/site-packages'
 * S: '/var/tmp/portage/www-client/uzbl-9999-r1/work/uzbl-9999'                                                                                                                                ... done!

```

Thank you.

**Comment by l29ah** [comment]
On Wed, Oct 12, 2016 at 12:34:11PM -0700, David wrote:
> When emergin uzbl i get the next error message:
> 
> ```
> Calculating dependencies \ * ERROR: www-client/uzbl-9999-r1::booboo failed (depend phase):
>  *   use() calls are not allowed in global scope
>  * 
>  * Call stack:
>  *             ebuild.sh, line 606:  Called source '/var/lib/layman/booboo/www-client/uzbl/uzbl-9999-r1.ebuild'
>  *   uzbl-9999-r1.ebuild, line  18:  Called use 'experimental'
>  *             ebuild.sh, line  78:  Called die
>  * The specific snippet of code:
>  *   		eval "${x}() { die \"\${FUNCNAME}() calls are not allowed in global scope\"; }"
>  * 
>  * If you need support, post the output of `emerge --info '=www-client/uzbl-9999-r1::booboo'`,
>  * the complete build log and the output of `emerge -pqv '=www-client/uzbl-9999-r1::booboo'`.
>  * Working directory: '/usr/lib64/python2.7/site-packages'
>  * S: '/var/tmp/portage/www-client/uzbl-9999-r1/work/uzbl-9999'                                                                                                                                ... done!

Should be fixed by 1a8b85c.

-- 
()  ascii ribbon campaign - against html mail
/\  http://arc.pasp.de/   - against proprietary attachments
