### ISSUE TITLE
www-client/uzbl-9999 has missing dependencies

### ISSUE THREAD

**Issue by Columbus240** [l29ah/booboo#29]
With the default USE flags (="browser tabbed") www-client/uzbl-9999 needs the following additional build dependencies on my system:

- dev-python/wheel
- dev-python/pip

I didn't check which are also runtime dependencies.

Also the compilation complains about pip not having a --prefix option. The following line got executed by the uzbl Makefile.
`pip3 install -I --prefix=/var/tmp/portage/www-client/uzbl-9999-r1/imge///usr --root=/var/tmp/portage/www-client/uzbl-9999-r1/image/ --install-option="" dist/uzbl-0.9.1+36.g1ce13a2c-py3-none-any.whl`

**Comment by l29ah** [comment]
Consider syncing the repo before filing bugs.

**Comment by Columbus240** [comment]
Sorry, for bothering then.
But the error with pip still appears.
I'll create a new issue, if you don't mind.

**Comment by l29ah** [comment]
Well, i couldn't reproduce it with USE=experimental. I'll try without.

**Comment by l29ah** [comment]
Couldn't reproduce it w/ either. Fixed a webkit dependency though. Post the full build log plz.

**Comment by Columbus240** [comment]
The error occurs on line 257 or 259 of the upstream Makefile.
[build.log](https://paste.pound-python.org/show/9C8CE5jPKymN42r3WLe0)

By the way, I noticed that the repo moved from "Dieterbe/uzbl" to "uzbl/uzbl".

**Comment by l29ah** [comment]
Do i get it right you have `dev-python/pip-9.0.1-r1` installed?

**Comment by Columbus240** [comment]
No, I got `dev-python/pip-7.1.2`. I'll try it with `9.0.1-r1` 'till you respond.

**Comment by Columbus240** [comment]
Still doesn't build with `9.0.1-r1`, but the error is different. Here I also include the [build.log](https://paste.pound-python.org/show/W78Kw1ry17AlgnNUFm49/).
A working uzbl with either one would be nice. Because without (some) work I can't reasonably try it out. Some paths seem to be hardcoded, and I don't want to search and replace them. I still wouldn't be able to install it with portage.

**Comment by l29ah** [comment]
On Tue, Apr 11, 2017 at 12:32:22PM -0700, Columbus240 wrote:
> Still doesn't build with `9.0.1-r1`, but the error is different. Here I also include the [build.log](https://paste.pound-python.org/show/W78Kw1ry17AlgnNUFm49/).
> A working uzbl with either one would be nice. Because without (some) work I can't reasonably try it out. Some paths seem to be hardcoded, and I don't want to search and replace them. I still wouldn't be able to install it with portage.

Uh oh. It seems that paludis doesn't punch me for such an atrocity. Dunno if i'll fix it in a timely manner tho as i've moved to palemoon/qutebrowser.

-- 
()  ascii ribbon campaign - against html mail
/\  http://arc.pasp.de/   - against proprietary attachments

**Comment by Columbus240** [comment]
I don't know why, but it builds now on my computer. It works.
