### ISSUE TITLE
net-im/telegram-cli doesn't build

### ISSUE THREAD

**Issue by chrboe** [l29ah/booboo#51]
Like #37, this is likely fixed by removing -Werror from the Makefile

**Comment by lexszero** [comment]
I don't have any Gentoo boxes anymore so I have no way to test it.

**Comment by chrboe** [comment]
Hold on, I'll send a patch

**Comment by l29ah** [comment]
fixed in 53ca1aea4147ddeecbc387dc1cf60b9b17d456f6
