### ISSUE TITLE
media-gfx/amide requires

### ISSUE THREAD

**Issue by skinkie** [l29ah/booboo#64]
gnome-base/libgnomecanvas
gnome-base/gconf
gnome-base/gnome-vfs

**Comment by skinkie** [comment]
There are some problems with ffmpeg. In addition to that:

```
alignment_mutual_information.c: In function 'calculate_mutual_information':
alignment_mutual_information.c:212:10: error: expected '(' before '__builtin_isinf_sign'
  212 |       if isinf(incremental_mi) {
```
Trivial fix with if (isinf(incremental_mi)) {

Sadly the application directly ends in an sigabort.

**Comment by l29ah** [comment]
Try sci-visualization/amide::imaging, it seems to be better supported.
