### ISSUE TITLE
linuxCNC?

### ISSUE THREAD

**Issue by RayOfLight1** [l29ah/booboo#66]
I see there is no manifest and when i do:
sudo ebuild linuxcnc-9999.ebuild manifest

Error(s) in metadata for 'sci-electronics/linuxcnc-9999':
  DEPEND: Invalid atom (Invalid use dep: '%PYTHON_USEDEP-NEEDS-TO-BE-USED-IN-PYTHON_GEN_COND_DEP%'), token 18
  RDEPEND: Invalid atom (Invalid use dep: '%PYTHON_USEDEP-NEEDS-TO-BE-USED-IN-PYTHON_GEN_COND_DEP%'), token 18

:(

**Comment by l29ah** [comment]
On Sun, Jul 19, 2020 at 06:57:05AM -0700, RayOfLight1 wrote:
> I see there is no manifest and when i do:
> sudo ebuild linuxcnc-9999.ebuild manifest
> 
> Error(s) in metadata for 'sci-electronics/linuxcnc-9999':
>   DEPEND: Invalid atom (Invalid use dep: '%PYTHON_USEDEP-NEEDS-TO-BE-USED-IN-PYTHON_GEN_COND_DEP%'), token 18
>   RDEPEND: Invalid atom (Invalid use dep: '%PYTHON_USEDEP-NEEDS-TO-BE-USED-IN-PYTHON_GEN_COND_DEP%'), token 18
> 
> :(

I'm sorry, the ebuild is bitrotten since i don't have linuxcnc installed for over a year now.

-- 
()  ascii ribbon campaign - against html mail
/\  http://arc.pasp.de/   - against proprietary attachments
