### ISSUE TITLE
media-sound/sonic  failed to install

### ISSUE THREAD

**Issue by reppkchen** [l29ah/booboo#67]
* Applying sonic-9999-fix-lib.patch ...                                 [ ok ]
 * ERROR: media-sound/sonic-9999::booboo failed (prepare phase):
 *   eapply_user (or default) must be called in src_prepare()!
 * 
 * Call stack:
 *            ebuild.sh, line  762:  Called __ebuild_main 'prepare'
 *   phase-functions.sh, line 1050:  Called __dyn_prepare
 *   phase-functions.sh, line  395:  Called die
 * The specific snippet of code:
 *   		die "eapply_user (or default) must be called in src_prepare()!"

**Comment by l29ah** [comment]
@gordon-quad ^

**Comment by l29ah** [comment]
fixed
