### ISSUE TITLE
Cannot install xkb-switch-9999::booboo - missing keyword

### ISSUE THREAD

**Issue by TheRealOne78** [l29ah/booboo#85]
Hi. I am trying to emerge "xkb-switch" but emerge tells me that there's a missing keyword.

What I am trying to execute:
```bash
doas emerge "=xkb-switch-9999::booboo" --autounmask-write
Calculating dependencies... done!
Dependency resolution took 1.55 s (backtrack: 0/20).


!!! All ebuilds that could satisfy "=xkb-switch-9999::booboo" have been masked.
!!! One of the following masked packages is required to complete your request:
- x11-apps/xkb-switch-9999::booboo (masked by: missing keyword)

For more information, see the MASKED PACKAGES section in the emerge
man page or refer to the Gentoo Handbook.
```

Maybe it's a skill issue. Either way, the emerge man page doesn't tell me, and looking at the .emerge file, everything looks OK to me...

**Comment by l29ah** [comment]
Live ebuilds can't be keyworded per Gentoo policy. To keyword them locally, you can use https://wiki.gentoo.org/wiki//etc/portage/package.accept_keywords
