### ISSUE TITLE
Deprecated eutils.eclass

### ISSUE THREAD

**Issue by chaotycznyzbyszek** [l29ah/booboo#87]
due to the lack of the file in portage tree there's an emerge error:

Calculating dependencies / * ERROR: dev-libs/libusb-0.1.12-r8::booboo failed (depend phase):
 *   eutils.eclass could not be found by inherit()
 * 
 * Call stack:
 *                 ebuild.sh, line 632:  Called source '/var/db/repos/booboo/dev-libs/libusb/libusb-0.1.12-r8.ebuild'
 *   libusb-0.1.12-r8.ebuild, line   7:  Called inherit 'eutils' 'libtool' 'autotools' 'toolchain-funcs' 'multilib-minimal'
 *                 ebuild.sh, line 277:  Called die
 * The specific snippet of code:
 *   		[[ -z ${location} ]] && die "${1}.eclass could not be found by inherit()"
 * 
 * If you need support, post the output of `emerge --info '=dev-libs/libusb-0.1.12-r8::booboo'`,
 * the complete build log and the output of `emerge -pqv '=dev-libs/libusb-0.1.12-r8::booboo'`.
 * Working directory: '/usr/lib/python3.12/site-packages'
 * S: '/var/tmp/portage/dev-libs/libusb-0.1.12-r8/work/libusb-0.1.12'
... done!

**Comment by l29ah** [comment]
I don't quite remember why i have libusb-0.1 at all. Do you need it for anything?

**Comment by chaotycznyzbyszek** [comment]
> I don't quite remember why i have libusb-0.1 at all. Do you need it for anything?

No, I have recent version from repos/gentoo. Thanks for quick reply!
